# Generated by Django 3.1 on 2020-12-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=50)),
                ('condition', models.CharField(max_length=50)),
                ('sale_price', models.IntegerField(null=True)),
                ('borrow_price', models.IntegerField(null=True)),
                ('availability', models.CharField(max_length=20)),
                ('image1', models.TextField()),
                ('image2', models.TextField()),
                ('poster_name', models.CharField(max_length=255)),
                ('poster_email', models.CharField(max_length=255)),
                ('views', models.IntegerField()),
                ('is_borrowed', models.CharField(default='No', max_length=5)),
                ('is_sold', models.CharField(default='No', max_length=5)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Dates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=5)),
                ('request_for', models.CharField(max_length=20)),
                ('borrowing_offer', models.IntegerField(blank=True)),
                ('buying_offer', models.IntegerField(blank=True)),
                ('message', models.CharField(max_length=500)),
                ('requester_name', models.CharField(max_length=255)),
                ('requester_email', models.CharField(max_length=255)),
                ('seller_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='pending', max_length=10)),
                ('response', models.CharField(blank=True, max_length=500, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('user_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('wishlist', models.JSONField(blank=True)),
            ],
        ),
    ]
