# Generated by Django 3.1 on 2020-12-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=50)),
                ('condition', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('availability', models.CharField(max_length=20)),
                ('image1', models.TextField()),
                ('image2', models.TextField()),
                ('posted_by', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('user_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('wishlist', models.JSONField(blank=True)),
            ],
        ),
    ]
