# Generated by Django 3.1 on 2020-12-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=5)),
                ('customer_email', models.CharField(max_length=255)),
                ('accepted', models.BooleanField()),
                ('seller_contact', models.CharField(blank=True, max_length=255)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
