# Generated by Django 3.1 on 2020-12-12 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='response',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='seller_contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
