# Generated by Django 3.1 on 2020-12-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_request_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Response',
        ),
        migrations.RemoveField(
            model_name='request',
            name='accepted',
        ),
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
