# Generated by Django 3.1 on 2020-12-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=500)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('publisher_name', models.CharField(max_length=200)),
                ('publisher_dept', models.CharField(max_length=200)),
                ('likes', models.IntegerField()),
                ('cover_photo', models.TextField()),
            ],
        ),
    ]
