# Generated by Django 3.0.5 on 2020-12-25 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.CharField(max_length=5000)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('publisher_name', models.CharField(max_length=200)),
                ('publisher_dept', models.CharField(blank=True, max_length=200)),
                ('publisher_email', models.CharField(max_length=200)),
                ('likes', models.IntegerField()),
                ('cover_photo', models.TextField()),
            ],
        ),
    ]
