# Generated by Django 3.1 on 2020-12-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='liked_blogs',
            field=models.JSONField(blank=True, default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='wishlist',
            field=models.JSONField(blank=True, default=[]),
            preserve_default=False,
        ),
    ]
